"""
Generate a presentation-quality infographic of the Dialogue Pipeline.
Uses real movie frames with actual InsightFace detections from pipeline runs.

Usage: uv run python docs/generate_pipeline_infographic.py
Output: docs/dialogue_pipeline_infographic.png

Requires: docs/real_frames/ directory with extracted frames and detections.json
(generated by docs/extract_real_frames.py on the GPU machine)
"""

import json
import os
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyArrowPatch, Ellipse
from matplotlib.gridspec import GridSpec
from PIL import Image
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FRAMES_DIR = os.path.join(SCRIPT_DIR, "real_frames")

# ── Style ──────────────────────────────────────────────────────────────
plt.rcParams.update({
    "figure.facecolor": "#0d1117",
    "axes.facecolor": "#161b22",
    "text.color": "#e6edf3",
    "axes.labelcolor": "#e6edf3",
    "xtick.color": "#8b949e",
    "ytick.color": "#8b949e",
    "font.family": "monospace",
    "font.size": 11,
})

ACCENT = "#58a6ff"
GREEN = "#3fb950"
ORANGE = "#d29922"
RED = "#f85149"
PURPLE = "#bc8cff"
CYAN = "#39d2c0"
PINK = "#f778ba"
GRAY = "#8b949e"
WHITE = "#e6edf3"
BG_DARK = "#0d1117"
BG_CARD = "#21262d"
BORDER = "#30363d"

BBOX_COLORS = [
    (88, 166, 255),    # blue
    (63, 185, 80),     # green
    (210, 153, 34),    # orange
    (188, 140, 255),   # purple
    (247, 120, 186),   # pink
    (57, 210, 192),    # cyan
    (248, 81, 73),     # red
    (255, 166, 87),    # amber
]

CHAR_COLORS = {
    "ID:18 (Ripley)": "#58a6ff",
    "ID:20 (Hicks)": "#3fb950",
    "ID:32 (Burke)": "#d29922",
    "ID:02 (Bishop)": "#bc8cff",
    "ID:22 (Hudson)": "#f778ba",
    "ID:37 (Vasquez)": "#39d2c0",
    "ID:44 (Gorman)": "#f85149",
    "ID:336 (Newt)": "#ffa657",
}

# ── Load real frames and detections ────────────────────────────────────
with open(os.path.join(FRAMES_DIR, "detections.json")) as f:
    det_meta = json.load(f)

frame_shape = det_meta["frame_shape"]  # [1080, 1920, 3]
img_h, img_w = frame_shape[0], frame_shape[1]

# Correct for pixel aspect ratio (Aliens DVD is 720x480 SAR 10:11, DAR 15:11)
# Display width = 720 * 10/11 ≈ 655 → display as 655x480
PIXEL_ASPECT_RATIO = 10 / 11  # SAR from ffprobe
display_w = int(img_w * PIXEL_ASPECT_RATIO)
display_h = img_h


def load_frame(prefix):
    """Load a frame PNG, corrected for pixel aspect ratio."""
    path = os.path.join(FRAMES_DIR, prefix)
    img = Image.open(path)
    # Resize to correct display aspect ratio
    img = img.resize((display_w, display_h), Image.LANCZOS)
    return np.array(img)


def get_detections(timestamp_key):
    """Get detection list for a timestamp."""
    return det_meta["detections"].get(timestamp_key, [])


# Find frames with most faces for best panels
det_counts = {k: len(v) for k, v in det_meta["detections"].items()}
sorted_frames = sorted(det_counts.items(), key=lambda x: -x[1])
# Best frames: 3-face, then 2-face ones
best_3face = [k for k, v in sorted_frames if v >= 3]
best_2face = [k for k, v in sorted_frames if v == 2]

print(f"Available frames: {det_counts}")
print(f"Best 3-face: {best_3face}, Best 2-face: {best_2face}")

# ── Figure setup ───────────────────────────────────────────────────────
fig = plt.figure(figsize=(30, 22), dpi=150)
fig.patch.set_facecolor(BG_DARK)

fig.text(0.5, 0.98, "SAM-Audio Dialogue Pipeline", fontsize=32, fontweight="bold",
         ha="center", va="top", color=WHITE, fontfamily="sans-serif")
fig.text(0.5, 0.963, "Per-Character Speech Isolation from Full-Length Movies",
         fontsize=15, ha="center", va="top", color=ACCENT, fontfamily="sans-serif")
fig.text(0.5, 0.95, "A100 80GB  |  Aliens (1986) 2h17m  |  8 Characters  |  3.3h Total",
         fontsize=12, ha="center", va="top", color=GRAY, fontfamily="monospace")

# Load filmstrip frames — evenly-spaced across the full movie
import glob
all_raw_frames = sorted(glob.glob(os.path.join(FRAMES_DIR, "frame_*_raw.png")),
                        key=lambda f: int(os.path.basename(f).split("_")[1]))
# Use the 16 evenly-spaced frames (every ~8.5 min across 2h17m)
filmstrip_timestamps = {300, 600, 900, 1200, 1480, 1800, 2400, 3000,
                        3600, 4200, 4800, 5400, 6000, 6600, 7200, 7800}
raw_frame_files = [f for f in all_raw_frames
                   if int(os.path.basename(f).split("_")[1]) in filmstrip_timestamps]

gs = GridSpec(3, 4, figure=fig, left=0.03, right=0.97, top=0.93, bottom=0.03,
              hspace=0.42, wspace=0.2)

rng = np.random.RandomState(42)


def draw_panel_bg(ax, title, subtitle=None, title_color=ACCENT):
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.set_xticks([])
    ax.set_yticks([])
    for spine in ax.spines.values():
        spine.set_color(BORDER)
        spine.set_linewidth(2)
    ax.set_facecolor(BG_CARD)
    ax.set_title(title, fontsize=14, fontweight="bold", color=title_color,
                 pad=12, fontfamily="sans-serif", loc="left")
    if subtitle:
        ax.set_title(subtitle, fontsize=9, color=GRAY, pad=12,
                     fontfamily="monospace", loc="right")


# ═══════════════════════════════════════════════════════════════════════
# Panel 1: Face Detection — REAL FRAMES
# ═══════════════════════════════════════════════════════════════════════
ax1 = fig.add_subplot(gs[0, 0])
draw_panel_bg(ax1, "PASS 0: Face Detection", "InsightFace RetinaFace")

# Use the 3-face frame (t=172s)
det_key = best_3face[0] if best_3face else best_2face[0]
det_ts = float(det_key)
raw_frame = load_frame(f"frame_{int(det_ts)}_raw.png")
faces = get_detections(det_key)

# Show the frame filling most of the panel
ax1.imshow(raw_frame, extent=[0.02, 0.98, 0.05, 0.78], aspect="auto")

# Draw real bounding boxes with scores
for i, face in enumerate(faces):
    x1, y1, x2, y2 = face["bbox"]
    score = face["score"]
    color_rgb = BBOX_COLORS[i % len(BBOX_COLORS)]
    color_hex = f"#{color_rgb[0]:02x}{color_rgb[1]:02x}{color_rgb[2]:02x}"

    # Convert pixel coords to display coords (corrected for SAR)
    dx1 = max(0, x1) * PIXEL_ASPECT_RATIO
    dx2 = min(img_w, x2) * PIXEL_ASPECT_RATIO
    ax_x1 = 0.02 + (dx1 / display_w) * 0.96
    ax_x2 = 0.02 + (dx2 / display_w) * 0.96
    # Y is inverted (image top=0 -> axes top=0.78)
    ax_y1 = 0.78 - (max(0, y1) / img_h) * 0.73
    ax_y2 = 0.78 - (min(img_h, y2) / img_h) * 0.73

    bx, by = min(ax_x1, ax_x2), min(ax_y1, ax_y2)
    bw, bh = abs(ax_x2 - ax_x1), abs(ax_y2 - ax_y1)

    rect = mpatches.FancyBboxPatch((bx, by), bw, bh,
                                    boxstyle="round,pad=0.005",
                                    linewidth=2.5, edgecolor=color_hex,
                                    facecolor="none")
    ax1.add_patch(rect)
    # Score label with background
    ax1.text(bx + bw / 2, by + bh + 0.02, f"{score:.2f}",
             fontsize=9, ha="center", color=color_hex,
             fontweight="bold", fontfamily="monospace",
             bbox=dict(boxstyle="round,pad=0.12", facecolor=BG_DARK,
                       alpha=0.85, edgecolor="none"))

# Stats
stats_text = f"4,092 detections  |  every 2s  |  17 min (CPU)  |  t={det_ts:.0f}s"
ax1.text(0.50, 0.92, stats_text, fontsize=7.5, ha="center", color=GRAY,
         fontfamily="monospace",
         bbox=dict(boxstyle="round,pad=0.25", facecolor=BG_DARK, edgecolor=BORDER,
                   alpha=0.9))


# ═══════════════════════════════════════════════════════════════════════
# Panel 2: Clustering — REAL face crops with t-SNE from actual embeddings
# ═══════════════════════════════════════════════════════════════════════
ax2 = fig.add_subplot(gs[0, 1])
draw_panel_bg(ax2, "PASS 0: ArcFace Clustering", "cosine d=0.6")

from matplotlib.offsetbox import OffsetImage, AnnotationBbox

# Load real face embeddings + t-SNE coords + cluster assignments
face_emb_path = os.path.join(FRAMES_DIR, "face_embeddings.json")
with open(face_emb_path) as f:
    face_emb_data = json.load(f)

real_faces = face_emb_data["faces"]
n_real_clusters = face_emb_data["n_clusters"]

# Normalize t-SNE coords to [0.05, 0.88] range for plotting
tsne_xs = np.array([f["tsne_x"] for f in real_faces])
tsne_ys = np.array([f["tsne_y"] for f in real_faces])
tsne_xs = 0.05 + 0.88 * (tsne_xs - tsne_xs.min()) / (tsne_xs.max() - tsne_xs.min() + 1e-8)
tsne_ys = 0.05 + 0.80 * (tsne_ys - tsne_ys.min()) / (tsne_ys.max() - tsne_ys.min() + 1e-8)

# Assign colors per cluster (main clusters get bright colors, singletons get gray)
cluster_ids = [f["cluster_id"] for f in real_faces]
cluster_sizes = {}
for cid in cluster_ids:
    cluster_sizes[cid] = cluster_sizes.get(cid, 0) + 1

# Sort clusters by size (largest first) for color assignment
sorted_clusters = sorted(cluster_sizes.keys(), key=lambda c: -cluster_sizes[c])
cluster_color_map = {}
bright_colors = [ACCENT, GREEN, ORANGE, PURPLE, PINK, CYAN, RED, "#ffa657"]
color_idx = 0
for cid in sorted_clusters:
    if cluster_sizes[cid] >= 2 and color_idx < len(bright_colors):
        cluster_color_map[cid] = bright_colors[color_idx]
        color_idx += 1
    else:
        cluster_color_map[cid] = GRAY

# Draw cluster boundary ellipses for multi-face clusters
for cid in sorted_clusters:
    if cluster_sizes[cid] < 3:
        continue
    color = cluster_color_map[cid]
    mask = np.array([f["cluster_id"] == cid for f in real_faces])
    cxs, cys = tsne_xs[mask], tsne_ys[mask]
    ax2.add_patch(Ellipse((np.mean(cxs), np.mean(cys)),
                           width=max(np.std(cxs) * 5.5, 0.08),
                           height=max(np.std(cys) * 5.5, 0.08),
                           facecolor=color, alpha=0.06, edgecolor=color,
                           linewidth=1, linestyle=":"))

# Place face crop thumbnails at t-SNE positions
FACE_CROPS_DIR = os.path.join(FRAMES_DIR, "face_crops")
thumb_size = 0.045  # size in axes coords

for i, face in enumerate(real_faces):
    crop_path = os.path.join(FACE_CROPS_DIR, face["crop_file"])
    if not os.path.exists(crop_path):
        continue
    crop_img = np.array(Image.open(crop_path))
    # Resize to small thumbnail for display
    pil_thumb = Image.fromarray(crop_img).resize((40, 40), Image.LANCZOS)
    thumb_arr = np.array(pil_thumb)

    cid = face["cluster_id"]
    color = cluster_color_map[cid]

    x, y = tsne_xs[i], tsne_ys[i]

    imagebox = OffsetImage(thumb_arr, zoom=0.55)
    imagebox.image.axes = ax2
    ab = AnnotationBbox(imagebox, (x, y), frameon=True,
                        bboxprops=dict(edgecolor=color, linewidth=1.5,
                                       facecolor=BG_DARK),
                        pad=0.1, zorder=5)
    ax2.add_artist(ab)

# Add cluster labels for main clusters
for cid in sorted_clusters:
    if cluster_sizes[cid] < 3:
        continue
    color = cluster_color_map[cid]
    mask = np.array([f["cluster_id"] == cid for f in real_faces])
    cxs, cys = tsne_xs[mask], tsne_ys[mask]
    label = f"Cluster {cid} ({cluster_sizes[cid]})"
    ax2.text(np.mean(cxs), np.mean(cys) + max(np.std(cys) * 3.5, 0.06),
             label, fontsize=8, ha="center", color=color, fontweight="bold",
             fontfamily="sans-serif",
             bbox=dict(boxstyle="round,pad=0.12", facecolor=BG_DARK, edgecolor=color,
                       alpha=0.9, linewidth=0.8), zorder=10)

ax2.text(0.5, 0.95, f"512-dim ArcFace | {len(real_faces)} detections | {n_real_clusters} clusters",
         fontsize=7.5, ha="center", color=GRAY, fontfamily="monospace",
         transform=ax2.transAxes)


# ═══════════════════════════════════════════════════════════════════════
# Panel 3: Mask Generation — REAL FRAMES with actual mask demo
# ═══════════════════════════════════════════════════════════════════════
ax3 = fig.add_subplot(gs[0, 2])
draw_panel_bg(ax3, "PASS 0: Mask Generation", "SAM3 / BBox+20%")

# Use Aliens frames with face detections for mask demo
mask_frames = [
    ("frame_1480_raw.png", "1480.0", 0),   # 3-face scene, first face
    ("frame_1480_raw.png", "1480.0", 1),   # 3-face scene, second face
    ("frame_1500_raw.png", "1500.0", 0),   # 2-face scene, first face
]

# Column headers
ax3.text(0.18, 0.93, "Input Frame", fontsize=9, ha="center", color=WHITE,
         fontweight="bold", fontfamily="sans-serif")
ax3.text(0.50, 0.93, "Binary Mask", fontsize=9, ha="center", color=WHITE,
         fontweight="bold", fontfamily="sans-serif")
ax3.text(0.82, 0.93, "Masked Output", fontsize=9, ha="center", color=WHITE,
         fontweight="bold", fontfamily="sans-serif")

char_labels = ["Char A", "Char B", "Char C"]
char_colors_list = [ACCENT, GREEN, ORANGE]

for i, (frame_file, det_key, face_idx) in enumerate(mask_frames):
    row_y = 0.72 - i * 0.25
    col_xs = [0.04, 0.36, 0.68]
    w, h = 0.28, 0.20
    color = char_colors_list[i]

    raw = load_frame(frame_file)
    dets = get_detections(det_key)

    if face_idx < len(dets):
        bbox = dets[face_idx]["bbox"]
        x1, y1, x2, y2 = bbox
        # Scale X coords from original pixel space to display space
        x1 = int(x1 * PIXEL_ASPECT_RATIO)
        x2 = int(x2 * PIXEL_ASPECT_RATIO)
        # Pad bbox by 20%
        bw, bh = x2 - x1, y2 - y1
        pad_x, pad_y = int(bw * 0.2), int(bh * 0.2)
        mx1 = max(0, x1 - pad_x)
        my1 = max(0, y1 - pad_y)
        mx2 = min(display_w, x2 + pad_x)
        my2 = min(display_h, y2 + pad_y)
    else:
        mx1, my1, mx2, my2 = display_w//4, display_h//4, 3*display_w//4, 3*display_h//4

    # Crop a region around the face for the mini frames
    # Use panel cell aspect ratio (w:h = 0.28:0.20 = 1.4:1) to match display
    panel_aspect = w / h  # 1.4
    cx, cy = (mx1 + mx2) // 2, (my1 + my2) // 2
    face_size = max(mx2 - mx1, my2 - my1)
    crop_h_px = int(face_size * 2)
    crop_w_px = int(crop_h_px * panel_aspect)
    cx1 = max(0, cx - crop_w_px // 2)
    cy1 = max(0, cy - crop_h_px // 2)
    cx2 = min(display_w, cx + crop_w_px // 2)
    cy2 = min(display_h, cy + crop_h_px // 2)
    cropped = raw[cy1:cy2, cx1:cx2]

    # Create mask (target=0, background=255)
    mask_img = np.full_like(cropped, 200)  # light gray background
    # Face region in mask coords
    face_in_crop_x1 = mx1 - cx1
    face_in_crop_y1 = my1 - cy1
    face_in_crop_x2 = mx2 - cx1
    face_in_crop_y2 = my2 - cy1
    face_in_crop_x1 = max(0, face_in_crop_x1)
    face_in_crop_y1 = max(0, face_in_crop_y1)
    face_in_crop_x2 = min(cropped.shape[1], face_in_crop_x2)
    face_in_crop_y2 = min(cropped.shape[0], face_in_crop_y2)
    mask_img[face_in_crop_y1:face_in_crop_y2, face_in_crop_x1:face_in_crop_x2] = 0

    # Create masked output (only face visible)
    masked_out = cropped.copy()
    # Darken everything outside the face bbox
    dark_mask = np.ones(cropped.shape[:2], dtype=bool)
    dark_mask[face_in_crop_y1:face_in_crop_y2, face_in_crop_x1:face_in_crop_x2] = False
    masked_out[dark_mask] = (masked_out[dark_mask] * 0.08).astype(np.uint8)

    # Draw all 3 columns
    for j, x0 in enumerate(col_xs):
        if j == 0:
            img_data = cropped
        elif j == 1:
            img_data = mask_img
        else:
            img_data = masked_out

        ax3.imshow(img_data, extent=[x0, x0 + w, row_y - h/2, row_y + h/2],
                   aspect="auto")
        edge_color = color if j != 1 else GRAY
        rect = mpatches.Rectangle((x0, row_y - h/2), w, h,
                                   linewidth=1.5, edgecolor=edge_color,
                                   facecolor="none", alpha=0.7)
        ax3.add_patch(rect)

    # Character label
    ax3.text(0.01, row_y, char_labels[i], fontsize=8, color=color, fontweight="bold",
             fontfamily="sans-serif", rotation=90, ha="center", va="center")

    # Arrows between columns
    for x_arrow in [0.33, 0.65]:
        ax3.annotate("", xy=(x_arrow + 0.02, row_y), xytext=(x_arrow - 0.01, row_y),
                     arrowprops=dict(arrowstyle="->", color=GRAY, lw=1.5))

# Convention
ax3.text(0.50, 0.05, "target = 0 (black)  |  video * mask.eq(0)",
         fontsize=8, ha="center", color=ACCENT, fontfamily="monospace", fontweight="bold",
         bbox=dict(boxstyle="round,pad=0.25", facecolor=BG_DARK, edgecolor=ACCENT,
                   alpha=0.9, linewidth=1.2))


# ═══════════════════════════════════════════════════════════════════════
# Panel 4: Optimization History
# ═══════════════════════════════════════════════════════════════════════
ax4 = fig.add_subplot(gs[0, 3])
draw_panel_bg(ax4, "Optimization History", "6 rounds", title_color=GREEN)

rounds = ["R1 Baseline", "R2 Range API", "R3 Batch API",
          "R4 90s windows", "R5 Visibility", "R6 Final"]
times = [393, 600, 390, 305, 197, 203]
colors_bar = [GRAY, RED, GRAY, ORANGE, GREEN, GREEN]

y_positions = np.arange(len(rounds))
bars = ax4.barh(y_positions, times, color=colors_bar, height=0.55, alpha=0.7,
                edgecolor=[c for c in colors_bar], linewidth=1.5)

for bar, c in zip(bars, colors_bar):
    ax4.barh(bar.get_y() + bar.get_height() * 0.3, bar.get_width(),
             height=bar.get_height() * 0.4, color=c, alpha=0.15)

ax4.set_yticks(y_positions)
ax4.set_yticklabels(rounds, fontsize=9, fontfamily="sans-serif")
ax4.set_xlim(0, 720)
ax4.set_xlabel("Total time (minutes)", fontsize=9, color=GRAY, fontfamily="sans-serif")
ax4.invert_yaxis()

for i, (t, c) in enumerate(zip(times, colors_bar)):
    h_val, m_val = divmod(t, 60)
    label = f" {h_val}h{m_val:02d}m"
    if i == 1:
        label += "  REGRESSION"
    ax4.text(t + 10, i, label, va="center", fontsize=9, color=c, fontweight="bold",
             fontfamily="monospace")

ax4.text(0.97, 0.03, "49% FASTER", fontsize=18, ha="right", va="bottom",
         color=GREEN, fontweight="bold", fontfamily="sans-serif",
         transform=ax4.transAxes,
         bbox=dict(boxstyle="round,pad=0.35", facecolor=BG_DARK, edgecolor=GREEN,
                   alpha=0.95, linewidth=2.5))
ax4.text(0.97, 0.15, "6h33m -> 3h23m", fontsize=10, ha="right", va="bottom",
         color=GRAY, fontfamily="monospace", transform=ax4.transAxes)


# ═══════════════════════════════════════════════════════════════════════
# Panel 5: Pass 1 — Dialogue Detection
# ═══════════════════════════════════════════════════════════════════════
ax5 = fig.add_subplot(gs[1, 0:2])
draw_panel_bg(ax5, "PASS 1: Text-Only Dialogue Detection",
              '97 chunks x 90s | prompt="speech"', title_color=ORANGE)

t = np.linspace(0, 90, 4000)
signal = np.zeros_like(t)
speech_regions = [(5, 12), (18, 25), (30, 38), (45, 52), (58, 62), (70, 78), (82, 88)]

for start, end in speech_regions:
    mask = (t >= start) & (t <= end)
    duration = end - start
    env = np.exp(-3 * ((t[mask] - (start + end) / 2) / (duration / 2)) ** 2)
    amp = 0.4 + 0.4 * rng.random()
    sig = np.zeros(mask.sum())
    for freq in rng.uniform(2, 15, 5):
        sig += rng.uniform(0.1, 0.4) * np.sin(2 * np.pi * freq * t[mask] + rng.uniform(0, 6.28))
    signal[mask] = amp * sig / np.abs(sig).max() * env

signal += rng.normal(0, 0.015, len(t))

x_coords = np.linspace(0.02, 0.98, len(t))
upper = 0.40 + signal * 0.22
lower = 0.40 - signal * 0.22

for start, end in speech_regions:
    x0 = 0.02 + (start / 90) * 0.96
    w = ((end - start) / 90) * 0.96
    ax5.axvspan(x0, x0 + w, ymin=0.2, ymax=0.85, facecolor=ACCENT, alpha=0.06)

ax5.fill_between(x_coords, upper, lower, color=ACCENT, alpha=0.5, linewidth=0)
ax5.plot(x_coords, upper, color=ACCENT, alpha=0.9, linewidth=0.6)
ax5.plot(x_coords, lower, color=ACCENT, alpha=0.9, linewidth=0.6)
ax5.axhline(y=0.40, color=GRAY, linewidth=0.5, linestyle=":", alpha=0.3)
ax5.text(0.995, 0.58, "-40 dB threshold", fontsize=7, color=RED, fontfamily="monospace",
         ha="right", alpha=0.7)

for start, end in speech_regions:
    x0 = 0.02 + (start / 90) * 0.96
    w = ((end - start) / 90) * 0.96
    rect = mpatches.FancyBboxPatch((x0, 0.06), w, 0.07, boxstyle="round,pad=0.005",
                                    facecolor=GREEN, alpha=0.65, edgecolor=GREEN, linewidth=0.8)
    ax5.add_patch(rect)

ax5.text(0.02, 0.68, "SAM-Audio separated speech", fontsize=9, color=ACCENT,
         fontfamily="monospace", fontweight="bold")
ax5.text(0.02, 0.02, "has_dialogue  (1s RMS > -40dB)", fontsize=9, color=GREEN,
         fontfamily="monospace", fontweight="bold")
ax5.text(0.98, 0.68, "Chunk 34/97  |  t = 50:00 - 51:30", fontsize=9, color=GRAY,
         fontfamily="monospace", ha="right")

for s in range(0, 91, 15):
    x = 0.02 + (s / 90) * 0.96
    ax5.text(x, 0.155, f"{s}s", fontsize=8, ha="center", color=GRAY, fontfamily="monospace")
    ax5.plot([x, x], [0.14, 0.17], color=GRAY, linewidth=0.8)
for s in range(0, 91, 5):
    x = 0.02 + (s / 90) * 0.96
    ax5.plot([x, x], [0.145, 0.16], color=GRAY, linewidth=0.3, alpha=0.5)


# ═══════════════════════════════════════════════════════════════════════
# Panel 6: Pass 2 — Visual Separation
# ═══════════════════════════════════════════════════════════════════════
ax6 = fig.add_subplot(gs[1, 2:4])
draw_panel_bg(ax6, "PASS 2: Visual Per-Character Separation",
              "~130 eligible char-chunks | ~75s each", title_color=PURPLE)

components = [
    ("DACVAE\nencode", 3, GRAY),
    ("T5 text", 2, ORANGE),
    ("CLIP vision\nencoder", 50, PURPLE),
    ("ODE solver\n16 diff. steps", 70, RED),
    ("DACVAE\ndecode", 10, GRAY),
]

x_pos = 0.04
total = sum(c[1] for c in components)
bar_y, bar_h = 0.65, 0.13

for name, dur, color in components:
    w = (dur / total) * 0.92
    rect = mpatches.FancyBboxPatch((x_pos, bar_y), w, bar_h,
                                    boxstyle="round,pad=0.004",
                                    facecolor=color, alpha=0.45, edgecolor=color, linewidth=1.5)
    ax6.add_patch(rect)
    ax6.plot([x_pos + 0.005, x_pos + w - 0.005], [bar_y + bar_h, bar_y + bar_h],
             color=color, linewidth=2, alpha=0.8)
    if w > 0.05:
        ax6.text(x_pos + w/2, bar_y + bar_h/2 + 0.01, name, fontsize=7.5,
                 ha="center", va="center", color=WHITE, fontweight="bold",
                 fontfamily="sans-serif", linespacing=1.3)
        ax6.text(x_pos + w/2, bar_y - 0.03, f"{dur}s", fontsize=9, ha="center",
                 color=color, fontweight="bold", fontfamily="monospace")
    x_pos += w

ax6.text(0.50, 0.84, "model.separate()  per character  (~75s  |  90s chunk  |  2,250 tokens)",
         fontsize=10, ha="center", color=WHITE, fontfamily="monospace",
         bbox=dict(boxstyle="round,pad=0.25", facecolor=BG_DARK, edgecolor=BORDER,
                   alpha=0.9, linewidth=1.2))

ax6.text(0.04, 0.48, "O(n\u00b2) Self-Attention Cost", fontsize=11, color=RED,
         fontweight="bold", fontfamily="sans-serif")
ax6.text(0.04, 0.43, "Key insight: halving chunk duration = 4x less attention work",
         fontsize=8, color=GRAY, fontfamily="sans-serif")

attn_data = [
    ("180s  (4500 tokens)", 20.25, 0.55, RED),
    ("120s  (3000 tokens)", 9.0, 0.245, ORANGE),
    ("90s   (2250 tokens)", 5.06, 0.14, GREEN),
]

for i, (label, val, w_frac, color) in enumerate(attn_data):
    y = 0.35 - i * 0.10
    rect = mpatches.FancyBboxPatch((0.30, y - 0.03), w_frac, 0.055,
                                    boxstyle="round,pad=0.005",
                                    facecolor=color, alpha=0.35,
                                    edgecolor=color, linewidth=1.2)
    ax6.add_patch(rect)
    rect2 = mpatches.FancyBboxPatch((0.30, y - 0.015), w_frac, 0.025,
                                     boxstyle="round,pad=0.003",
                                     facecolor=color, alpha=0.5, edgecolor="none")
    ax6.add_patch(rect2)
    ax6.text(0.29, y, label, fontsize=9, ha="right", va="center",
             color=GRAY, fontfamily="monospace")
    ax6.text(0.30 + w_frac + 0.015, y, f"{val}M ops", fontsize=9, ha="left", va="center",
             color=color, fontweight="bold", fontfamily="monospace")

ax6.annotate("4x\nreduction", xy=(0.92, 0.15), xytext=(0.92, 0.37),
             fontsize=12, color=GREEN, fontweight="bold", fontfamily="sans-serif",
             ha="center", va="center",
             arrowprops=dict(arrowstyle="-|>", color=GREEN, lw=2.5, mutation_scale=20))


# ═══════════════════════════════════════════════════════════════════════
# Panel 7: Speaking Timeline — REAL DATA from R6 pipeline run
# ═══════════════════════════════════════════════════════════════════════
ax7 = fig.add_subplot(gs[2, :])

# Load real speaking timeline from R6 results
timeline_path = os.path.join(FRAMES_DIR, "speaking_timeline.json")
with open(timeline_path) as f:
    timeline_data = json.load(f)

real_stats = timeline_data["statistics"]
draw_panel_bg(ax7, "OUTPUT: Per-Character Speaking Timeline",
              f"dialogue_metadata.json | {real_stats['dialogue_percentage']}% dialogue | "
              f"{int(real_stats['total_dialogue_seconds'])}s total | "
              f"{real_stats['num_gaps']} gaps",
              title_color=CYAN)

# Show a 10-minute window with natural turn-taking
# Score: many segments + many unique characters - penalty for simultaneous speakers
movie_duration = timeline_data.get("movie_duration", 8220)
window_duration = 600  # 10 minutes
best_start = 4680  # default fallback (~78:00)
best_score = -1
for test_start in range(0, movie_duration - window_duration, 60):
    test_end = test_start + window_duration
    seg_count = 0
    char_set = set()
    for cid, cdata in timeline_data["per_character"].items():
        for s, e in cdata["segments"]:
            if s < test_end and e > test_start:
                seg_count += 1
                char_set.add(cid)
    # Count seconds with 3+ simultaneous speakers (looks unnatural)
    bad_seconds = 0
    for t in range(test_start, test_end, 2):  # sample every 2s for speed
        n_speaking = 0
        for cid, cdata in timeline_data["per_character"].items():
            for s, e in cdata["segments"]:
                if s <= t < e:
                    n_speaking += 1
                    break
        if n_speaking >= 3:
            bad_seconds += 1
    score = seg_count + len(char_set) * 5 - bad_seconds * 4
    if score > best_score:
        best_score = score
        best_start = test_start

window_start = best_start
window_end = window_start + window_duration

# Character display order (by total speaking time, descending)
char_order = sorted(timeline_data["per_character"].keys(),
                    key=lambda c: -timeline_data["per_character"][c]["total_speaking_seconds"])

# Map character IDs to display names and colors
char_id_to_name = {
    "18": "Ripley", "20": "Hicks", "32": "Burke", "2": "Bishop",
    "22": "Hudson", "37": "Vasquez", "44": "Gorman", "336": "Newt",
}
char_id_to_color_key = {
    "18": "ID:18 (Ripley)", "20": "ID:20 (Hicks)", "32": "ID:32 (Burke)",
    "2": "ID:02 (Bishop)", "22": "ID:22 (Hudson)", "37": "ID:37 (Vasquez)",
    "44": "ID:44 (Gorman)", "336": "ID:336 (Newt)",
}

# ── Filmstrip row at top of timeline panel ─────────────────────────────
n_strip_frames = len(raw_frame_files)
if n_strip_frames > 0:
    # Size the strip so frames fill the available width (0.88 axes units)
    # Calculate how tall the strip needs to be for n frames to span the width
    ax7_bbox = ax7.get_position()
    panel_w_inches = ax7_bbox.width * fig.get_figwidth()
    panel_h_inches = ax7_bbox.height * fig.get_figheight()
    frame_dar = display_w / display_h  # ~1.36
    gap_ax = 0.003
    avail_w_ax = 0.88
    # Each frame: width = height_ax * frame_dar * (panel_h/panel_w)
    # n * (height_ax * frame_dar * panel_h/panel_w + gap_ax) = avail_w_ax
    aspect_factor = frame_dar * panel_h_inches / panel_w_inches
    strip_h = (avail_w_ax - n_strip_frames * gap_ax) / (n_strip_frames * aspect_factor)
    strip_h = min(strip_h, 0.28)  # allow tall enough to fill width
    strip_y_top = 0.94
    strip_y_bot = strip_y_top - strip_h

    # Filmstrip background band
    ax7.axhspan(strip_y_bot - 0.01, strip_y_top + 0.01, facecolor="#111111", edgecolor="none")

    # Sprocket holes
    sprocket_color = "#2a2a2a"
    n_sprockets = n_strip_frames * 4
    for sx in np.linspace(0.09, 0.97, n_sprockets):
        for sy in [strip_y_top + 0.003, strip_y_bot - 0.015]:
            ax7.add_patch(mpatches.FancyBboxPatch(
                (sx - 0.003, sy), 0.006, 0.012,
                boxstyle="round,pad=0.001",
                facecolor=sprocket_color, edgecolor="#444444",
                linewidth=0.3, alpha=0.7))

    # Edge lines
    ax7.plot([0.085, 0.975], [strip_y_top + 0.015, strip_y_top + 0.015],
             color="#333333", linewidth=1.5)
    ax7.plot([0.085, 0.975], [strip_y_bot - 0.015, strip_y_bot - 0.015],
             color="#333333", linewidth=1.5)

    # Place frame thumbnails — correct aspect ratio
    # Frame is display_w x display_h. We need to fit within strip_h height.
    # The axes are 0-1 in both x and y, but the panel is not square,
    # so we need the figure-level aspect to convert properly.
    ax7_bbox = ax7.get_position()
    panel_w_inches = ax7_bbox.width * fig.get_figwidth()
    panel_h_inches = ax7_bbox.height * fig.get_figheight()
    # strip_h in axes coords → inches
    strip_h_inches = strip_h * panel_h_inches
    # Each frame width in inches at correct aspect
    frame_aspect = display_w / display_h  # ~1.36
    frame_w_inches = strip_h_inches * frame_aspect
    # Convert back to axes x-coords
    frame_w_ax = frame_w_inches / panel_w_inches
    gap = 0.003
    total_strip_w = n_strip_frames * (frame_w_ax + gap)
    x_start = 0.09 + (0.88 - total_strip_w) / 2  # center the strip
    x_start = max(0.09, x_start)

    # Load subtitles for overlay
    subs_path = os.path.join(FRAMES_DIR, "subtitles.json")
    subtitles = {}
    if os.path.exists(subs_path):
        with open(subs_path) as f:
            subtitles = json.load(f)

    for i, fpath in enumerate(raw_frame_files):
        frame_img = load_frame(os.path.basename(fpath))
        x = x_start + i * (frame_w_ax + gap)
        ax7.imshow(frame_img,
                   extent=[x, x + frame_w_ax, strip_y_bot, strip_y_top],
                   aspect="auto", zorder=3)
        ax7.add_patch(mpatches.Rectangle(
            (x, strip_y_bot), frame_w_ax, strip_h,
            linewidth=0.8, edgecolor="#555555", facecolor="none", zorder=4))

        # Subtitle overlay at bottom of each frame
        ts = int(os.path.basename(fpath).split("_")[1])
        sub_data = subtitles.get(str(ts), {})
        sub_text = sub_data.get("text", "").strip()
        if sub_text:
            # Truncate to fit frame width (~12-15 chars per line)
            max_chars = 18
            lines = []
            words = sub_text.split()
            line = ""
            for word in words:
                if len(line) + len(word) + 1 <= max_chars:
                    line = (line + " " + word).strip()
                else:
                    lines.append(line)
                    line = word
                if len(lines) >= 2:  # max 2 lines
                    break
            if line and len(lines) < 2:
                lines.append(line)

            sub_display = "\n".join(lines)
            # Semi-transparent background bar + white text
            ax7.text(x + frame_w_ax / 2, strip_y_bot + strip_h * 0.08,
                     sub_display, fontsize=4.5, ha="center", va="bottom",
                     color="white", fontfamily="sans-serif", fontweight="bold",
                     linespacing=1.1, zorder=6,
                     bbox=dict(boxstyle="square,pad=0.15", facecolor="black",
                               alpha=0.7, edgecolor="none"))

    ax7.text(0.075, (strip_y_top + strip_y_bot) / 2, "Frames",
             fontsize=7, ha="right", va="center", color=GRAY,
             fontfamily="monospace", fontweight="bold")

# ── Character speaking lanes ───────────────────────────────────────────
# Start character lanes below the filmstrip
lane_height = 0.065
start_y = strip_y_bot - 0.05 if n_strip_frames > 0 else 0.88

for i, cid in enumerate(char_order):
    cdata = timeline_data["per_character"][cid]
    color_key = char_id_to_color_key.get(cid, "ID:18 (Ripley)")
    color = CHAR_COLORS.get(color_key, GRAY)
    char_name = char_id_to_name.get(cid, f"Char {cid}")
    y = start_y - i * lane_height

    # Label with speaking stats
    total_s = int(cdata["total_speaking_seconds"])
    ax7.text(0.075, y, char_name, fontsize=10, ha="right", va="center",
             color=color, fontweight="bold", fontfamily="sans-serif")
    ax7.text(0.076, y - 0.02, f"ID:{cid} ({total_s}s)", fontsize=6, ha="left", va="top",
             color=GRAY, fontfamily="monospace", alpha=0.6)
    ax7.plot([0.09, 0.97], [y, y], color=BORDER, linewidth=0.5, alpha=0.4)

    # Draw real speaking segments within window
    for seg_start, seg_end in cdata["segments"]:
        # Clip to window
        s = max(seg_start, window_start)
        e = min(seg_end, window_end)
        if s >= e:
            continue
        x0 = 0.09 + ((s - window_start) / window_duration) * 0.88
        w = ((e - s) / window_duration) * 0.88
        w = max(w, 0.002)  # minimum visible width
        # Glow
        glow = mpatches.FancyBboxPatch((x0 - 0.001, y - 0.028), w + 0.002, 0.056,
                                        boxstyle="round,pad=0.003",
                                        facecolor=color, alpha=0.12, edgecolor="none")
        ax7.add_patch(glow)
        # Main bar
        rect = mpatches.FancyBboxPatch((x0, y - 0.022), w, 0.044,
                                        boxstyle="round,pad=0.003",
                                        facecolor=color, alpha=0.75,
                                        edgecolor=color, linewidth=0.5)
        ax7.add_patch(rect)

# Real gaps from R6 data
gap_count = 0
for gap_start, gap_end in timeline_data["gaps"]:
    gs_clamped = max(gap_start, window_start)
    ge_clamped = min(gap_end, window_end)
    gap_dur = ge_clamped - gs_clamped
    if gap_dur < 8:  # only show gaps >= 8s to avoid clutter
        continue
    x0 = 0.09 + ((gs_clamped - window_start) / window_duration) * 0.88
    x1 = 0.09 + ((ge_clamped - window_start) / window_duration) * 0.88
    ax7.axvspan(x0, x1, ymin=0.12, ymax=0.92, facecolor=CYAN, alpha=0.04)
    ax7.plot([x0, x0], [0.12, 0.92], color=CYAN, linewidth=0.6, linestyle="--", alpha=0.25)
    ax7.plot([x1, x1], [0.12, 0.92], color=CYAN, linewidth=0.6, linestyle="--", alpha=0.25)
    if gap_dur >= 15:  # label larger gaps
        ax7.text((x0 + x1) / 2, 0.11, f"AD\n{int(gap_dur)}s", fontsize=6, ha="center",
                 va="top", color=CYAN, fontfamily="monospace", alpha=0.5, linespacing=1.2)
    gap_count += 1

# Time axis
for s_offset in range(0, window_duration + 1, 60):
    x = 0.09 + (s_offset / window_duration) * 0.88
    abs_time = window_start + s_offset
    m, s = divmod(int(abs_time), 60)
    ax7.text(x, 0.04, f"{m}:{s:02d}", fontsize=8, ha="center", color=GRAY,
             fontfamily="monospace")
    ax7.plot([x, x], [0.06, 0.09], color=GRAY, linewidth=1)

for s_offset in range(0, window_duration + 1, 15):
    x = 0.09 + (s_offset / window_duration) * 0.88
    ax7.plot([x, x], [0.07, 0.09], color=GRAY, linewidth=0.3, alpha=0.4)

win_m1 = window_start // 60
win_m2 = window_end // 60
ax7.text(0.5, 0.01,
         f"Real R6 pipeline output  |  Showing {win_m1}:00-{win_m2}:00 "
         f"({window_duration // 60} min window)  |  "
         f"8 tracked characters  |  RMS threshold: -40 dB",
         fontsize=8, ha="center", color=GRAY, fontfamily="monospace")


# ═══════════════════════════════════════════════════════════════════════
# Flow arrows
# ═══════════════════════════════════════════════════════════════════════
arrow_kw = dict(arrowstyle="-|>", color=ACCENT, lw=2.5, mutation_scale=20)

fig.patches.append(FancyArrowPatch(
    (0.25, 0.625), (0.25, 0.605),
    transform=fig.transFigure, **arrow_kw))
fig.text(0.27, 0.612, "audio + face clusters", fontsize=9, color=ACCENT,
         fontfamily="monospace", fontweight="bold")

fig.patches.append(FancyArrowPatch(
    (0.72, 0.625), (0.72, 0.605),
    transform=fig.transFigure, **arrow_kw))
fig.text(0.74, 0.612, "masks per character", fontsize=9, color=ACCENT,
         fontfamily="monospace", fontweight="bold")

fig.patches.append(FancyArrowPatch(
    (0.50, 0.33), (0.50, 0.31),
    transform=fig.transFigure, **arrow_kw))
fig.text(0.52, 0.317, "per-character speech segments + quality scores", fontsize=9,
         color=ACCENT, fontfamily="monospace", fontweight="bold")

# VRAM badge
fig.text(0.97, 0.015, "VRAM: 57/80 GB  |  sam-audio-base-tv  |  48kHz mono",
         fontsize=9, ha="right", va="bottom", color=GRAY, fontfamily="monospace",
         bbox=dict(boxstyle="round,pad=0.3", facecolor=BG_CARD, edgecolor=BORDER,
                   alpha=0.9, linewidth=1))

# ── Save ───────────────────────────────────────────────────────────────
output_path = os.path.join(SCRIPT_DIR, "dialogue_pipeline_infographic.png")
fig.savefig(output_path, dpi=150, bbox_inches="tight",
            facecolor=BG_DARK, edgecolor="none", pad_inches=0.2)
print(f"Saved to {output_path}")
w_px = fig.get_size_inches()[0] * 150
h_px = fig.get_size_inches()[1] * 150
print(f"Size: {w_px:.0f} x {h_px:.0f} px")
plt.close()
